_format_version: "3.0"
plugins:
- config:
    bandwidth_metrics: false
    latency_metrics: true
    per_consumer: false
    status_code_metrics: true
    upstream_health_metrics: false
  enabled: true
  name: prometheus
  protocols:
  - grpc
  - grpcs
  - http
  - https
  tags:
  - prometheus
